### ISSUE TITLE
observed differences of tutorial data visualizations

### ISSUE THREAD

**Issue by Mechah** [micom-dev/q2-micom#5]
Hi again,
I observed a stronger clustering of taxa after running the following commands in the community tutorial:
qiime micom exchanges-per-taxon --i-results crc_growth.qza --o-visualization crc_niche.qzv
Were there any modifications with the --p-n-neighbors and --p-min-dist parameters before producing the example plot?

**Comment by cdiener** [comment]
Sorry for that! I recently changed how `qiime micom grow` calculates the fluxes to make it work more like what we did in the paper (get fluxes from the minimal import space rather than using the somewhat arbitrary solution from the growth simulation). This does change the result somewhat for all the exchange visualizations. I am still planning to update the tutorial with a more recent run.

**Comment by cdiener** [comment]
Tutorial was now updated.
